export function useExportPDF() {
  const exportToPDF = (title: string, dateRange: string, content: string) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title} - StaffTrack Report</title>
        <style>
          body { font-family: 'Inter', system-ui, sans-serif; padding: 40px; color: #1a1a2e; }
          h1 { font-size: 24px; margin-bottom: 4px; }
          .subtitle { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
          th { background: #f3f4f6; text-align: left; padding: 8px 12px; font-size: 12px; text-transform: uppercase; color: #6b7280; border-bottom: 2px solid #e5e7eb; }
          td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
          .kpi-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 24px; }
          .kpi-item { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; }
          .kpi-value { font-size: 24px; font-weight: 700; }
          .kpi-label { font-size: 12px; color: #6b7280; }
          .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 16px; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class="subtitle">StaffTrack Report • ${dateRange} • Generated ${new Date().toLocaleDateString()}</div>
        ${content}
        <div class="footer">Generated by StaffTrack KPI Dashboard</div>
      </body>
      </html>
    `);

    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  };

  return { exportToPDF };
}
